name: Build on windows.
on:
  release:
    types: [published]
jobs:
  build:

    runs-on: windows-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Download CPDK 
        run: Invoke-WebRequest https://download.microsoft.com/download/1/7/6/176909b0-50f2-4df3-b29b-830a17ea7e38/CPDK_RELEASE_UPDATE/cpdksetup.exe -OutFile cpdksetup.exe

      - name: Unattened install of CPDK
        run: ./cpdksetup.exe /features + /q /log ./install-log.txt

      - name: CPDK Check
        run: start-sleep 20; type ./install-log.txt; dir 'c:\program files (x86)\windows kits\10\include\'

      - name: Build app for release
        run: msbuild EIDCredentialProvider.sln -t:rebuild -property:Configuration=Release /p:Platform=x64

      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with: 
          script-file: Installer/Installerx64.nsi
          arguments: "/V3"

      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: Installer/EIDInstallx64.exe